#STANDALONE_CC := /opt/Xilinx/Tools//SDK/2017.2/gnu/arm/lin/bin/arm-xilinx-eabi-gcc
#LINUX_CC :=/opt/Xilinx//Tools/SDK/2017.2/gnu/aarch32/lin/gcc-arm-linux-gnueabi/bin/arm-linux-gnueabihf-g++
STANDALONE_CC := /local/workspace/tools/xilinx_2016.4/SDK/2016.4/gnu/aarch32/lin/gcc-arm-linux-gnueabi/bin/arm-linux-gnueabihf-gcc
LINUX_CC := /local/workspace/tools/xilinx_2016.4/SDK/2016.4/gnu/aarch32/lin/gcc-arm-linux-gnueabi/bin/arm-linux-gnueabihf-g++

#VIVADO_VERSION := 2017.2
#VIVADO_PATH := /opt/Xilinx/Tools//Vivado
#VIVADO_BIN :=$(VIVADO_PATH)/$(VIVADO_VERSION)/bin/vivado
#XMD:=/opt/Xilinx/Tools//SDK/2015.2/bin/xmd


VIVADO_VERSION := 2017.2
VIVADO_PATH := /local/workspace/tools/xilinx/Vivado
VIVADO_BIN :=$(VIVADO_PATH)/$(VIVADO_VERSION)/bin/vivado
XMD:=/local/workspace/tools/xilinx/SDK/2017.2/bin/xmd




